server:
  port: 8189
  servlet:
#    context-path: /app
    context-path: /web-market-core

utils:
  cart:
    prefix: SPRING_WEB_

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false


integrations:
  cart-service:
    url: http://localhost:5555/cart
    timeouts:
      connection: 2000
      read: 11000
      write: 2000


