server:
  port: 8167
  servlet:
    context-path: /web-market-stats

# если хранить в Redis
utils:
  cart:
    prefix: REMARKET_STATS_

integrations:
  core-service:
    url: http://localhost:5555/core
    timeouts:
      connection: 2000
      read: 11000
      write: 2000
  cart-service:
    url: http://localhost:5555/cart
    timeouts:
      connection: 2000
      read: 11000
      write: 2000





















