server:
  port: 8167
  servlet:
    context-path: /web-market-stats

utils:
  cart:
    prefix: REMARKET_STATS_

integrations:
  core-service:
    url: http://localhost:5555/core
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000
  cart-service:
    url: http://localhost:5555/cart
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000





















